SELECT COUNTRY.Code AS CountryCode, COUNTRY.Name AS CountryName, COUNT(CITY.Name) AS Cities
FROM COUNTRY
JOIN CITY ON COUNTRY.Code = CITY.CountryCode
WHERE COUNTRY.Name LIKE 'United States%'
GROUP BY COUNTRY.Code, COUNTRY.Name;

SELECT Name, MAX(LIFEEXPECTANCY) AS LIFE_EXPECTANCY
FROM COUNTRY
GROUP BY NAME
ORDER BY LIFE_EXPECTANCY DESC

SELECT COUNTRY.Name AS CountryName, CITY.Name AS Cities
FROM COUNTRY
JOIN CITY ON COUNTRY.Code = CITY.CountryCode
WHERE CITY.Name LIKE '%NEW%'

SELECT NAME, POPULATION
FROM CITY 
ORDER BY POPULATION DESC
LIMIT 10

SELECT NAME, POPULATION
FROM CITY 
WHERE POPULATION >= '2000000'
ORDER BY POPULATION DESC

SELECT NAME
FROM CITY 
WHERE NAME LIKE 'BE%'


SELECT NAME, POPULATION
FROM CITY 
WHERE POPULATION BETWEEN '500000' AND '1000000'
ORDER BY POPULATION DESC

SELECT NAME
FROM CITY 
ORDER BY NAME ASC